<?php
namespace app\common\model\home;

use think\Model;

class HomeModel extends Model
{
    protected $name = "home";
    protected $autoWriteTimestamp = true;

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::event("before_update", function($model){
            if(isset($model->home_id) && isset($model->wallpaper)){
                HomeModel::rmWallpaperByid($model->home_id);
            }
        });
        self::event("before_delete", function($model){
            if(isset($model->home_id)){
                HomeModel::rmWallpaperByid($model->home_id);
            }
        });
    }

    /**
     * 根据ID删除壁纸
     * @param int $id 管理员ID
     */
    public static function rmWallpaperByid($id){
        $vo = HomeModel::field("wallpaper")->find($id);
        if($vo && $vo['avatar']){
            FileHelper::helper()->unlink($vo['wallpaper']);
        }
    }

    /**
     * 解散家庭
     * @param int $home_id
     * @return bool
     */
    public static function remove(int $home_id){
        $model = new HomeModel();
        $res1 = HomeModel::destroy($home_id);
        $res2 = HomeLeaguerModel::where("home_id", $home_id)->delete();
        $res3 = HomeLeaguerInviteModel::where("home_id", $home_id)->delete();
        $res4 = HomeDeviceProductModel::where("home_id", $home_id)->delete();
        if($res1 && $res2 && $res3 && $res4){
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * 校验用户是不是家庭创建人
     * @param int $home_id 家庭ID
     * @param int $user_id 用户ID
     */
    public static function checkCreater($home_id, $user_id){
        $creater_id = HomeModel::where("home_id", $home_id)->value("creater_id");
        if(creater_id === $user_id){
            return true;
        }
        else{
            return false;
        }
    }

}
