<?php

namespace app\common\model\admin;

use filehelper\FileHelper;
use helper\Helper;
use think\Model;

class AdminModel extends Model
{
    protected $name = "admin";
    protected $autoWriteTimestamp = true;
    protected $hidden = ['password', 'salt'];

    protected function getStatusTextAttr($val, $data){
        $status = $data['status'];
        $texts = [1=>'正常', 4=>'已禁用'];
        return $texts[$status];
    }

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::event("before_update", function($model){
            if(isset($model->ad_id) && isset($model->avatar)){
                AdminModel::rmAvatarByid($model->ad_id);
            }
        });
        self::event("before_delete", function($model){
            if(isset($model->ad_id)){
                AdminModel::rmAvatarByid($model->ad_id);
            }
        });
    }

    /**
     * 生成管理员密码
     * @param string $password 密码明文
     * @param string $salt 加密盐
     * @return string
     */
    public static function makePassword($password, $salt){
        return md5(md5($password).$salt);
    }

    /**
     * 根据提交信息创建或更新管理员信息
     * @param int $ad_id 管理员ID，为0时表示插入管理员，大于0时表示更新管理员
     * @param array $input 输入数据
     * @return object
     */
    public static function createOrUpdate($ad_id, $input){
        if($ad_id === 0){ //插入管理员
            if(isset($input['ad_id'])) unset($input['ad_id']);
            $salt = Helper::random(6);
            $input['password'] = AdminModel::makePassword($input['password'], $salt);
            $input['salt'] = $salt;
            $result = AdminModel::create($input);
        }else{ //更新管理员
            $input["ad_id"] = $ad_id;
            //校验密码
            if(!empty($input['password'])){
                $salt = AdminModel::where("ad_id", $ad_id)->value("salt");
                $input['password'] = AdminModel::makePassword($input['password'], $salt);
            }
            else{
                unset($input['password']);
            }
            $result = AdminModel::update($input);
        }
        return $result;
    }

    /**
     * 根据管理员ID删除用户头像
     * @param int $id 管理员ID
     */
    public static function rmAvatarByid($id){
        $vo = AdminModel::field("avatar")->find($id);
        if($vo && $vo['avatar']){
            FileHelper::helper()->unlink($vo['avatar']);
        }
    }

    //获取用户默认头像
    public static function getDefaultAvatar(){
        return DEFAULT_AVATAR;
    }

    /**
     * 根据管理员ID获取登录用户信息
     * @param int $ad_id
     * @return object
     */
    public static function getLoginUser($ad_id){
        $admin = AdminModel::get($ad_id);
        if($admin['avatar'] === ''){
            $admin['avatar'] = AdminModel::getDefaultAvatar();
        }
        else{
            $admin['avatar'] = FileHelper::helper()->getWebsitePath($admin['avatar']);
        }
        if($admin['ad_name'] === ''){
            $admin['ad_name'] = $admin['ad_account'];
        }
        return $admin;
    }

    /**
     * 获取当前登录的管理员ID
     */
    public static function getLogignAdId(){
        return (int)session("ad_id");
    }
}
